import {Meteor} from 'meteor/meteor';
// I want to make insert and remove methods for transactions
import {check} from 'meteor/check';
import { TransactionsCollection } from './transaction';

Meteor.methods({
  'transactions.insert'(transaction) {
    check(transaction, {
      senderUsername: String,
      receiverUsername: String,
      amount: Number,
      // createdAt will be auto-generated by schema
    });

    // Insert the transaction into the collection
    return TransactionsCollection.insert(transaction);
  },

  'transactions.remove'(transactionId) {
    check(transactionId, String);
    
    // Remove the transaction from the collection
    return TransactionsCollection.remove(transactionId);
  }
});